spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lunches?allowMultiQueries=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: org.gjt.mm.mysql.Driver
